# Generated by Django 5.1.5 on 2025-03-12 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placamap384',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='placamap384',
            name='projeto',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='app.projeto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placamap384',
            name='empresa',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='app.empresa'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='placamap384',
            unique_together={('empresa', 'projeto', 'placa_origem', 'placa_destino', 'quadrante')},
        ),
    ]
